package seedu.address.model.util;

import static seedu.address.logic.commands.PhotoCommand.DEFAULT_PHOTO_PATH;

import java.util.HashSet;
import java.util.Set;

import seedu.address.commons.exceptions.IllegalValueException;
import seedu.address.model.AddressBook;
import seedu.address.model.ReadOnlyAddressBook;
import seedu.address.model.person.Address;
import seedu.address.model.person.Birthday;
import seedu.address.model.person.Email;
import seedu.address.model.person.Gender;
import seedu.address.model.person.MatricNo;
import seedu.address.model.person.Name;
import seedu.address.model.person.Person;
import seedu.address.model.person.Phone;
import seedu.address.model.person.PhotoPath;
import seedu.address.model.person.Remark;
import seedu.address.model.person.exceptions.DuplicatePersonException;
import seedu.address.model.person.timetable.Timetable;
import seedu.address.model.tag.Tag;

/**
 * Contains utility methods for populating {@code AddressBook} with sample data.
 */
public class SampleDataUtil {
    public static Person[] getSamplePersons() {
        try {
            return new Person[]{
                new Person(new Name("Labayna Neil Brian Narido"), new Gender("Male"), new MatricNo("A0155006R"),
                        new Phone("96474278"), new Email("neilbrian.nl@gmail.com"),
                        new Address("Blk 630, Yishun St 61"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH), getTagSet("CS2101", "CS2103T"),
                        new Birthday("02101995")),
                new Person(new Name("Fan Yuting"), new Gender("Female"), new MatricNo(""),
                        new Phone("96855667"), new Email("fyt0616@gmail.com"),
                        new Address("Prince George Park Residences NUS"),
                        new Timetable(""),
                        new Remark("[Likes playing Dota 2]"), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("CS2105", "CS2101", "CS2103T"), new Birthday("16061998")),
                new Person(new Name("Tsai Yu Hsuan"), new Gender("Female"), new MatricNo("A0163331N"),
                        new Phone("95569202"), new Email("cindy93@gmail.com"),
                        new Address("7 Serangoon Avenue 2, #13-07"),
                        new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH), getTagSet("CS2101", "CS2103T"),
                        new Birthday("18081993")),
                new Person(new Name("Zachary Tang"), new Gender("Male"), new MatricNo("A0133788N"),
                        new Phone("91676489"), new Email("zachtang@gmail.com"),
                        new Address("Blk 43 Marine Crescent, #24-02"),
                        new Timetable(""),
                        new Remark("[Can't drink coffee]"), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("CS2101", "CS2103T"), new Birthday("06121995")),
                new Person(new Name("Isabel Tan"), new Gender("Female"), new MatricNo("A0466707R"),
                        new Phone("92492021"), new Email("isabel.tan@gmail.com"),
                        new Address("Blk 47 Tampines Street 20, #17-35"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH), getTagSet("ComputingClub"),
                        new Birthday("07121998")),
                new Person(new Name("Thomas Spencer"), new Gender("Male"), new MatricNo("A0155531K"),
                        new Phone("92624417"), new Email("royb@example.com"),
                        new Address("RC4 NUS UTown"), new Timetable(""),
                        new Remark("[From London]"), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("ExchangeStudent", "Business"), new Birthday("05111998")),
                new Person(new Name("Bobby Chin"), new Gender("Male"), new MatricNo("A0177348L"),
                        new Phone("99635723"), new Email("chinnybob@gmail.com"),
                        new Address("Blk 320, Ang Mo Kio St 32"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "Sociology"), new Birthday("01101994")),
                new Person(new Name("Buena Pflug"), new Gender("Male"), new MatricNo("A8021087A"),
                        new Phone("96478540"), new Email("buenapflug@example.com"),
                        new Address("Blk 407 Pasir Ris Street 11, #08-21"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Computing", "ComputingClub"), new Birthday("12051994")),
                new Person(new Name("Marlin Nathaniel"), new Gender("Female"), new MatricNo("A6530242P"),
                        new Phone("96399876"), new Email("marlinnathaniel@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "ComputingClub"), new Birthday("20101994")),
                new Person(new Name("Madalene Mcphearson"), new Gender("Male"), new MatricNo("A6276320L"),
                        new Phone("99308005"), new Email("madalenemcphearson@example.com"),
                        new Address("41 Buangkok Walk"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "CS2010"), new Birthday("25021993")),
                new Person(new Name("Kathline Guida"), new Gender("Male"), new MatricNo("A6255001M"),
                        new Phone("95510830"), new Email("kathlineguida@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS2010"), new Birthday("25031996")),
                new Person(new Name("Young Marley"), new Gender("Male"), new MatricNo("A9593986K"),
                        new Phone("99985685"), new Email("youngmarley@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("25121991")),
                new Person(new Name("Barbar Messineo"), new Gender("Male"), new MatricNo("A4508648O"),
                        new Phone("97946512"), new Email("barbarmessineo@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "NUSSU"), new Birthday("12031997")),
                new Person(new Name("Lucilla Awong"), new Gender("Female"), new MatricNo("A7988084F"),
                        new Phone("92998480"), new Email("lucillaawong@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "NUSSU"), new Birthday("25021993")),
                new Person(new Name("Tai Yeung"), new Gender("Male"), new MatricNo("A3331882P"),
                        new Phone("95552142"), new Email("taiyeung@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1330"), new Birthday("25101996")),
                new Person(new Name("Migdalia Valencia"), new Gender("Male"), new MatricNo("A9295628L"),
                        new Phone("99455678"), new Email("migdaliavalencia@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1330"), new Birthday("01061991")),
                new Person(new Name("Almeda Abboud"), new Gender("Female"), new MatricNo("A1153115U"),
                        new Phone("97162527"), new Email("almedaabboud@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1330"), new Birthday("12021991")),
                new Person(new Name("Jeannine Dillingham"), new Gender("Female"), new MatricNo("A6235773Z"),
                        new Phone("94095860"), new Email("jeanninedillingham@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "CS3216"), new Birthday("25121995")),
                new Person(new Name("Jule Mcphatter"), new Gender("Male"), new MatricNo("A6451322V"),
                        new Phone("93158669"), new Email("julemcphatter@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "MA1101R"), new Birthday("20051997")),
                new Person(new Name("Ilene Billiot"), new Gender("Female"), new MatricNo("A6546528N"),
                        new Phone("91270334"), new Email("ilenebilliot@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "CS3216"), new Birthday("12041997")),
                new Person(new Name("Cleveland Hem"), new Gender("Male"), new MatricNo("A7289927O"),
                        new Phone("95920561"), new Email("clevelandhem@example.com"),
                        new Address("Blk 407 Pasir Ris Street 11, #08-21"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "ComputingClub"), new Birthday("12101997")),
                new Person(new Name("Daisey Woolsey"), new Gender("Female"), new MatricNo("A2475823I"),
                        new Phone("98237912"), new Email("daiseywoolsey@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1101R"), new Birthday("20021997")),
                new Person(new Name("Nakisha Mcgranahan"), new Gender("Male"), new MatricNo("A4815877X"),
                        new Phone("98136314"), new Email("nakishamcgranahan@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "ComputingClub"), new Birthday("20051992")),
                new Person(new Name("Joella Render"), new Gender("Male"), new MatricNo("A9154693F"),
                        new Phone("94362607"), new Email("joellarender@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "ComputingClub"), new Birthday("01041994")),
                new Person(new Name("Contessa Purvines"), new Gender("Male"), new MatricNo("A5914297C"),
                        new Phone("98239719"), new Email("contessapurvines@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "ComputingClub"), new Birthday("20051997")),
                new Person(new Name("Sonia Asay"), new Gender("Male"), new MatricNo("A1468255N"),
                        new Phone("91062884"), new Email("soniaasay@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "Friend"), new Birthday("25121993")),
                new Person(new Name("Cecily Dumais"), new Gender("Female"), new MatricNo("A1818792R"),
                        new Phone("98426504"), new Email("cecilydumais@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("01021997")),
                new Person(new Name("Janice Akridge"), new Gender("Female"), new MatricNo("A2152541D"),
                        new Phone("95515400"), new Email("janiceakridge@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS2010"), new Birthday("25051995")),
                new Person(new Name("Columbus Womack"), new Gender("Female"), new MatricNo("A8278556A"),
                        new Phone("99654400"), new Email("columbuswomack@example.com"),
                        new Address("46 Lavender Crescent"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "Friend"), new Birthday("20121997")),
                new Person(new Name("Shaniqua Glasgow"), new Gender("Male"), new MatricNo("A3801537G"),
                        new Phone("94558305"), new Email("shaniquaglasgow@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "CS2010"), new Birthday("15041997")),
                new Person(new Name("Faviola Barbera"), new Gender("Male"), new MatricNo("A4896672K"),
                        new Phone("99558789"), new Email("faviolabarbera@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Computing", "CS3216"), new Birthday("01101995")),
                new Person(new Name("Carey Kyger"), new Gender("Female"), new MatricNo("A1697326H"),
                        new Phone("96447651"), new Email("careykyger@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "ComputingClub"), new Birthday("20011997")),
                new Person(new Name("Rudolf Mcdougall"), new Gender("Female"), new MatricNo("A3348607T"),
                        new Phone("98250590"), new Email("rudolfmcdougall@example.com"),
                        new Address("41 Buangkok Walk"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "ComputingClub"), new Birthday("25021997")),
                new Person(new Name("Marina Morlan"), new Gender("Female"), new MatricNo("A7161257H"),
                        new Phone("94329400"), new Email("marinamorlan@example.com"),
                        new Address("6 Kallang Lane, #08-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "NUSSU"), new Birthday("25031992")),
                new Person(new Name("Laurette Langlinais"), new Gender("Male"), new MatricNo("A2861448I"),
                        new Phone("97041380"), new Email("laurettelanglinais@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("25041992")),
                new Person(new Name("Devora Brundige"), new Gender("Female"), new MatricNo("A4613403B"),
                        new Phone("98395576"), new Email("devorabrundige@example.com"),
                        new Address("Blk 407 Pasir Ris Street 11, #08-21"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "CS2010"), new Birthday("20031992")),
                new Person(new Name("Luther Hollabaugh"), new Gender("Male"), new MatricNo("A8748300N"),
                        new Phone("94321025"), new Email("lutherhollabaugh@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "ComputingClub"), new Birthday("20011994")),
                new Person(new Name("Letha Fletcher"), new Gender("Female"), new MatricNo("A4225613S"),
                        new Phone("94505329"), new Email("lethafletcher@example.com"),
                        new Address("Blk 407 Pasir Ris Street 11, #08-21"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "Friend"), new Birthday("15031996")),
                new Person(new Name("Chaya Mcgrail"), new Gender("Female"), new MatricNo("A9299486I"),
                        new Phone("98109171"), new Email("chayamcgrail@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "MA1101R"), new Birthday("25041991")),
                new Person(new Name("Gilberto Docherty"), new Gender("Male"), new MatricNo("A4123755P"),
                        new Phone("92146527"), new Email("gilbertodocherty@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Computing", "MA1101R"), new Birthday("25011991")),
                new Person(new Name("Dottie Pillai"), new Gender("Female"), new MatricNo("A2920721O"),
                        new Phone("91690505"), new Email("dottiepillai@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Computing", "Friend"), new Birthday("15121995")),
                new Person(new Name("Alexa Wolf"), new Gender("Male"), new MatricNo("A2883137M"),
                        new Phone("99650356"), new Email("alexawolf@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("25011993")),
                new Person(new Name("Rosana Kyer"), new Gender("Female"), new MatricNo("A4914813H"),
                        new Phone("93217892"), new Email("rosanakyer@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS2010"), new Birthday("01101996")),
                new Person(new Name("Cherelle Hayman"), new Gender("Female"), new MatricNo("A3763904E"),
                        new Phone("95877073"), new Email("cherellehayman@example.com"),
                        new Address("Blk 16 Serangoon Gardens Street 76, #02-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "Friend"), new Birthday("20121993")),
                new Person(new Name("Rheba Gosnell"), new Gender("Female"), new MatricNo("A8015035B"),
                        new Phone("95437303"), new Email("rhebagosnell@example.com"),
                        new Address("6 Kallang Lane, #08-15"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS2010"), new Birthday("01011997")),
                new Person(new Name("Earl Vick"), new Gender("Male"), new MatricNo("A2717625E"),
                        new Phone("95107274"), new Email("earlvick@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "MA1101R"), new Birthday("20051996")),
                new Person(new Name("Madelene Gregerson"), new Gender("Female"), new MatricNo("A2720995D"),
                        new Phone("98707399"), new Email("madelenegregerson@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "CS3216"), new Birthday("15041997")),
                new Person(new Name("Charla Running"), new Gender("Male"), new MatricNo("A3094496I"),
                        new Phone("91559974"), new Email("charlarunning@example.com"),
                        new Address("Blk 122 Aljunied Lane, #04-26"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Computing", "CS3216"), new Birthday("25121997")),
                new Person(new Name("Verda Whitlatch"), new Gender("Female"), new MatricNo("A1486036X"),
                        new Phone("92836460"), new Email("verdawhitlatch@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Arts", "Friend"), new Birthday("15031996")),
                new Person(new Name("Merrilee Schwenk"), new Gender("Female"), new MatricNo("A4419530F"),
                        new Phone("95620381"), new Email("merrileeschwenk@example.com"),
                        new Address("Blk 192 Lorong 4 MacPherson, #09-20"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "NUSSU"), new Birthday("12121996")),
                new Person(new Name("Lakeshia Petree"), new Gender("Male"), new MatricNo("A6191020C"),
                        new Phone("91633742"), new Email("lakeshiapetree@example.com"),
                        new Address("Blk 209 Lorong 1 Dunearn, #10-16"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "ComputingClub"), new Birthday("12061997")),
                new Person(new Name("Sheba Galang"), new Gender("Female"), new MatricNo("A8914799Y"),
                        new Phone("92484439"), new Email("shebagalang@example.com"),
                        new Address("Blk 287 Tampines Street 71, #10-22"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Engineering", "MA1101R"), new Birthday("15061995")),
                new Person(new Name("Victor Amsden"), new Gender("Female"), new MatricNo("A8944332L"),
                        new Phone("98378279"), new Email("victoramsden@example.com"),
                        new Address("41 Buangkok Walk"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Science", "MA1330"), new Birthday("25031997")),
                new Person(new Name("Ka Logan"), new Gender("Female"), new MatricNo("A7399272F"),
                        new Phone("91734195"), new Email("kalogan@example.com"),
                        new Address("Blk 16 Bukit Panjang Street 85, #13-04"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "Friend"), new Birthday("20121994")),
                new Person(new Name("Wendi Fabre"), new Gender("Male"), new MatricNo("A9233557Y"),
                        new Phone("95222279"), new Email("wendifabre@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS3216"), new Birthday("25011991")),
                new Person(new Name("Monika Bence"), new Gender("Female"), new MatricNo("A6557233X"),
                        new Phone("95977917"), new Email("monikabence@example.com"),
                        new Address("Blk 21 Hougang Street 80, #14-25"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "MA1101R"), new Birthday("20041995")),
                new Person(new Name("Grazyna Greaney"), new Gender("Male"), new MatricNo("A7247724W"),
                        new Phone("91142218"), new Email("grazynagreaney@example.com"),
                        new Address("Blk 330 Kallang Street 73, #05-17"), new Timetable(""),
                        new Remark(""), new PhotoPath(DEFAULT_PHOTO_PATH),
                        getTagSet("Business", "CS2010"), new Birthday("25031995")),
            };
        } catch (IllegalValueException e) {
            throw new AssertionError("sample data cannot be invalid", e);
        }
    }

    public static ReadOnlyAddressBook getSampleAddressBook() {
        try {
            AddressBook sampleAb = new AddressBook();
            for (Person samplePerson : getSamplePersons()) {
                sampleAb.addPerson(samplePerson);
            }
            return sampleAb;
        } catch (DuplicatePersonException e) {
            throw new AssertionError("sample data cannot contain duplicate persons", e);
        }
    }

    /**
     * Returns a tag set containing the list of strings given.
     */
    public static Set<Tag> getTagSet(String... strings) throws IllegalValueException {
        HashSet<Tag> tags = new HashSet<>();
        for (String s : strings) {
            tags.add(new Tag(s));
        }
        return tags;
    }
}
